name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Install dotenv
        run: pip install python-dotenv
      - name: Install dependencies
        run: |
          poetry install
          poetry add pylint --group dev
          poetry add robotframework
      - name: Initialize database
        run: python3 src/initialize_database.py
      - name: Run tests
        run: |
          poetry run coverage run --branch -m pytest
          poetry run robot src/tests
      - name: Run pylint
        run: poetry run pylint src
      - name: Coverage report
        run: poetry run coverage xml
      - name: Coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
